# Statically link the Microsoft Visual C++ runtime on Windows.
#
# By default the MSVC target links the CRT dynamically, so the binary needs VCRUNTIME140.dll from
# the Visual C++ Redistributable and fails to start on a clean Windows machine without it
# ("VCRUNTIME140.dll was not found"). Static linking bundles the runtime into the executable, so it
# runs on any Windows with no redistributable to install -- fixing first-run failures across EVERY
# distribution channel (npm launcher, scoop, winget, direct download), not just one manifest. This
# is the standard posture for distributed Rust Windows binaries (ripgrep, fd, etc.). Linux and macOS
# are unaffected.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
